######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 26 18:42:11 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += GDialog.h GMain.h
SOURCES += GDialog.cc GMain.cc Grader.cc
